---
# Verify if firewalld service is installed/present
- name: Verify Firewalld is present
  command: systemctl is-enabled firewalld
  register: result
  failed_when: false

# Disable and stop firewalld as it will break the SE
- name: Avi SE | Prepare | Disable and stop Firewalld
  service: name="firewalld" state="stopped" enabled="no"
  when: result.stdout == "enabled"
