---

- name: change default admin password on cluster build when subscription
  uri:
    url: "https://{{ ansible_ssh_host }}/api/useraccount"
    method: PUT
    user: "{{ avi_username }}"
    password: "{{ avi_default_password }}"
    return_content: yes
    body: {"old_password":"{{ avi_default_password }}", password: "{{ avi_password }}"}
    body_format: json
    force_basic_auth: yes
    validate_certs: false
    status_code: 200
    timeout: 120
  when: ( avi_change_default | default(false ) | bool )
