---
con_deploy_type: docker
con_package_deploy: true # For local installation - default set to false and uses docker hub image
con_package_source: ~/avi-images/controller_docker.tgz
con_package_dest: /tmp/controller_docker.tgz
con_cores: 2
con_memory_gb: "{{ ansible_memtotal_mb // 1024 }}"
con_disk_gb: 10
con_controller_ip: "{{ ansible_default_ipv4.address }}"
con_fresh_install: false # Removes config and does clean install - requires that AVI controller is installed otherwise fails
con_force_deploy: false # Reploys Docker container without deleting config
