---
# se_dpdk tasks file for avinetworks.avise
- name: Avi SE | DPDK | Install PCI Utils
  package: name=pciutils

- name: Avi SE | DPDK | Set facts
  set_fact:
    se_old_dpdk: "{{ se_version|version_compare('16.3.0', '<') }}"
    se_new_dpdk: "{{ se_version|version_compare('16.3.0', '>=') }}"
    se_klm_ver: "{{ ansible_kernel | regex_replace('-.*', '') }}"

- block:
    - name: Avi SE | DPDK | < 16.3 | Configure DPDK Pre Parameters
      set_fact:
        se_dpdk_pre: >
          rmmod igb_uio; rmmod rte_kni; modprobe uio; insmod /opt/avi/kmod/igb_uio.ko;
          insmod /opt/avi/kmod/rte_kni.ko; mkdir -p /mnt/huge; umount /mnt/huge; rm /mnt/huge/*;
          mount -t hugetlbfs nodev /mnt/huge
      when: se_old_dpdk
    - name: Avi SE | DPDK | >= 16.3 | Configure DPDK Pre Parameters
      set_fact:
        se_dpdk_pre: >
          modprobe uio;
          mkdir -p /mnt/huge; umount /mnt/huge; rm /mnt/huge/*; mount -t hugetlbfs nodev /mnt/huge
      when: se_new_dpdk
  when: se_dpdk_pre is undefined

- name: Avi SE | DPDK | Configure DPDK Post Parameters
  set_fact:
    se_dpdk_post: "rmmod igb_uio; rmmod rte_kni; umount /mnt/huge"
  when: se_dpdk_post is undefined

- name: Avi SE | DPDK | Check for supported network interface cards"
  shell: lspci | grep "Ethernet" | grep "Intel Corporation" | egrep -i "{{ se_dpdk_supported_nics }}"
  register: se_dpdk_test_array
  changed_when: false

- name: Avi SE | DPDK | Create destination directories
  file: path={{ item }} state=directory mode=0755
  with_items:
    - /tmp/dpdk_klms
    - /opt/avi/kmod

- name: Avi SE | DPDK | Copy and Unarchive the DPDK KLMS
  unarchive: src={{ se_dpdk_klms_file }} dest=/tmp/dpdk_klms

- name: Avi SE | DPDK | Check that DPDK KLMS exist for the current kernel | 1/2.
  stat: path=/tmp/dpdk_klms/precompiled-klms/{{ ansible_kernel }}
  register: se_ansible_kernel_dpdk_klms
  failed_when: false

- name: Avi SE | DPDK | Check that DPDK KLMS exist for the current kernel | 2/2.
  stat: path=/tmp/dpdk_klms/precompiled-klms/{{ se_klm_ver }}
  when: not se_ansible_kernel_dpdk_klms.stat.exists
  register: se_klm_ver_dpdk_klms
  failed_when: false

- name: Avi SE | DPDK | Failed to find supported DPDK KLMS for current kernel.
  fail: msg="Could not find DPDK KLMS for {{ se_klm_ver }} or {{ ansible_kernel }}"
  when: not se_ansible_kernel_dpdk_klms.stat.exists and not se_klm_ver_dpdk_klms.stat.exists

- name: Avi SE | DPDK | Copy DPDK KLMS | 1/2
  shell: cp /tmp/dpdk_klms/precompiled-klms/{{ ansible_kernel }}/* /opt/avi/kmod/
  when: se_ansible_kernel_dpdk_klms.stat.exists

- name: Avi SE | DPDK | Copy DPDK KLMS | 2/2
  shell: cp /tmp/dpdk_klms/precompiled-klms/{{ se_klm_ver }}/* /opt/avi/kmod/
  when: not se_ansible_kernel_dpdk_klms.stat.exists and se_klm_ver_dpdk_klms.stat.exists
